package hu.totalbattlecalc.domain.enumeration;

/**
 * The FeatureName enumeration.
 */
public enum FeatureName {
    HUMAN,
    RANGED,
    MELEE,
    MOUNTED,
    FLYING,
    SIEGE_ENGINE,
    GUARDSMAN,
    SCOUT,
    SPECIALIST,
    ENGINEER,
    BEAST,
    DRAGON,
    GIANT,
    ELEMENTAL,
    STRENGTH_AGAINST_MELEE,
    STRENGTH_AGAINST_MOUNTED,
    STRENGTH_AGAINST_RANGED,
    STRENGTH_AGAINST_FLYING,
    STRENGTH_AGAINST_FORTIFICATION,
    STRENGTH_AGAINST_SIEGE_ENGINE,
    STRENGTH_AGAINST_DRAGON,
    STRENGTH_AGAINST_ELEMENTAL,
    STRENGTH_AGAINST_BEAST,
    STRENGTH_AGAINST_HUMAN,
    STRENGTH_DOUBLED_AGAINST_PLAYER,
    STRENGTH_AGAINST_FORTIFICATION_BY_20_TIMES,
    CHANCE_TO_DEAL_DOUBLE_DAMAGE,
    INITIATIVE_IN_SIEGE_5
}
